# Generated by Django 5.2.4 on 2025-08-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_payment_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="stripe_payment_url",
            new_name="link",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="stripe_price_id",
            new_name="session_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="stripe_product_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="stripe_session_id",
        ),
    ]
