# Generated by Django 5.2.4 on 2025-08-05 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_course_price_lesson_price"),
        ("users", "0010_rename_stripe_payment_url_payment_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="materials.course",
            ),
        ),
    ]
