# Generated by Django 5.2.4 on 2025-08-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_payment_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="product_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="product_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
