# Generated by Django 5.2.4 on 2025-08-05 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_course_price_lesson_price"),
        ("users", "0012_payment_product_id_payment_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="materials.course",
            ),
            preserve_default=False,
        ),
    ]
