# Generated by Django 5.2.4 on 2025-07-21 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="уроки",
                to="materials.course",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Ссылка на видео"
            ),
        ),
    ]
